CREATE DATABASE MapaSkills;

USE MapaSkills;

CREATE TABLE TC (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`)
  );

CREATE TABLE SUBDIVISAO_TC (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(20) NOT NULL,
  `TC_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_SUBDIVISAO_TC_TC`
    FOREIGN KEY (`TC_ID`)
    REFERENCES `TC` (`ID`)
 );

CREATE TABLE CARGO (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(20) NOT NULL,
  `SUBDIVISAO_TC_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_CARGO_SUBDIVISAO_TC1`
    FOREIGN KEY (`SUBDIVISAO_TC_ID`)
    REFERENCES `SUBDIVISAO_TC` (`ID`)
);

CREATE TABLE TECNOLOGIA (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`)
  );

CREATE TABLE SKILL (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `CARGO_ID` INT NOT NULL,
  `TECNOLOGIA_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_SKILL_CARGO1`
    FOREIGN KEY (`CARGO_ID`)
    REFERENCES `CARGO` (`ID`),
  CONSTRAINT `fk_SKILL_TECNOLOGIA1`
    FOREIGN KEY (`TECNOLOGIA_ID`)
    REFERENCES `TECNOLOGIA` (`ID`)
);